# Generated by Django 3.0.7 on 2022-04-24 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('visitor', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('date_time', models.DateTimeField()),
            ],
        ),
    ]
